version: "3"

vars:
  PROJECT_CODE: TCGA-storage
  BUILD_LOCATION: ./build

tasks:
  default:
    task: run

  run:
    cmds:
      - cmd: go get
      - task: start
      - cmd: go run .

  start:
    cmd: docker-compose up -d

  stop:
    cmd: docker-compose stop

  build:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - cmd: mkdir -p {{.BUILD_LOCATION}}
      - cmd: cp -r ./wwwroot {{.BUILD_LOCATION}}
      - cmd: go build -o {{.BUILD_LOCATION}}/{{.PROJECT_CODE}}

  clean:
    cmd: rm -rf {{.BUILD_LOCATION}}/*

  rebuild:
    cmds:
      - task: clean
      - task: build
